export const LANG_EN_VALUES = {
  'nav.home': 'Home',
  'nav.profile': 'My profile',
  'nav.favorites': 'My favorites',
  'nav.bazaar': 'Ideas bazaar',
  'nav.activities': 'Activities (workshops, events, projects)',
  'nav.membership': 'Membership',
  'nav.propose': 'Submit an idea',
  'nav.fablab': 'Fablab',
  'nav.it': 'Italian',
  'nav.en': 'English',
  'nav.rules': 'Rules',
  'nav.logout': 'Logout',
  'nav.login': 'Login',

  'loading.load': 'Loading...',
  'loading.login': 'Login',

  'errorPage.title': 'Error - La Scuola Open Source',
  'errorPage.text': 'ERROR {{code}}',

  'favorites.title': 'Your favorites - La Scuola Open Source',
  'favorites.heading': `Your <strong>favorites</strong>`,
  'favorites.users': 'People',
  'favorites.ideas': 'Ideas and projects',
  'favorites.activities': 'Activities',

  'home.title': 'La Scuola Open Source',

  'home.welcome.title': 'Benvenuto a bordo!',
  'home.welcome.body': `
    Il <b>Gestionale per Nuove Istituzioni</b><br />
    Connette <b>persone, idee, progetti e competenze</b><br />
    per generare <b>nuove possibilità</b>.
  `,

  'home.complete.profile.txt': 'Completa la tua registrazione:',
  'home.complete.profile.btn.profile': `<i class="sos-icon edit"></i> Completa il tuo profilo`,
  'home.complete.profile.btn.member': `<i class="sos-icon edit"></i> Scopri i piani di membership`,

  'home.search.value': `<b>People</b> / <b>Ideas</b> / <b>Activities</b>`,
  'home.search.skills': `<b>Skills</b>`,
  'home.search.btn': 'Search',
  'home.search.skills.show': 'Show search for skills',
  'home.search.skills.hide': 'Hide search for skills',
  'home.search.skills.matchAll': 'Ricerca chi ha tutte le competenze selezionate',
  'home.search.noResult': 'The research produced no results.',
  'home.search.users': 'People',
  'home.search.ideas': 'Ideas',
  'home.search.activities': 'Activities',

  'card.user.skills': 'Skills',
  'card.user.email': 'E-mail',
  'card.user.tel': 'Telephone',

  'card.idea.topics': 'Topics',
  'card.idea.type': 'Type',
  'card.idea.creator': 'Proposer',

  'card.activity.topics': 'Topics',
  'card.activity.startDate': 'Date',
  'card.activity.skills': 'Skills',
  'card.activity.type': 'Type',

  'profile.title': '{{user}} - La Scuola Open Source',
  'profile.title.me': 'My profile - La Scuola Open Source',
  'profile.edit.firstName': 'First name',
  'profile.edit.lastName': 'Last name',
  'profile.edit.title': 'Your role',
  'profile.edit.bio': 'Your bio',
  'profile.edit.skills': 'making, coding, design...',
  'profile.edit.telephone': '+39 123456789',
  'profile.edit.email': 'user@email.com',
  'profile.edit.city': 'City',
  'profile.edit.city.search': 'Search city',
  'profile.edit.city.empty': 'Leave empty',
  'profile.edit.city.other': 'Outside of Italy',
  'profile.edit.city.noneFound': 'No cities found',
  'profile.alert.changedEmail': `Follow the link at <b>{{email}}</b> to confirm your new email address`,
  'profile.skills': 'Skills:',
  'profile.telephone': 'Telephone:',
  'profile.email': 'Email:',
  'profile.city': 'City:',
  'profile.favorites.remove': 'Remove from favorites',
  'profile.favorites.add': 'Add to favorites',
  'profile.favorites': 'See favorites',

  'profile.skill.add': 'Add',

  'profile.reservations': 'Fablab Reservation',
  'profile.reservations.title': 'FabLab Machinery Reservation',
  'profile.reservations.machine': 'Machine',
  'profile.reservations.operator': 'Operator',
  'profile.reservations.dates': 'Dates',
  'profile.reservations.totalPrice': 'Total price',


  'bazaar.title': 'Ideas bazaar - La Scuola Open Source',
  'bazaar.heading': `<strong>Ideas</strong> <strong>bazaar</strong>`,
  'bazaar.subhead': 'Submit, search, discuss an idea or a project',

  'bazaar.filters.framework.teaching_framework': 'Teaching',
  'bazaar.filters.framework.research_framework': 'Research',
  'bazaar.filters.framework.entertainment_framework': 'Entertainment',
  'bazaar.filters.framework.all': 'All',

  'bazaar.filters.audience': 'Public',
  'bazaar.filters.audience.kids': 'Kids',
  'bazaar.filters.audience.teenagers': 'Teenagers',
  'bazaar.filters.audience.students': 'Students',
  'bazaar.filters.audience.researchers': 'Researcher',
  'bazaar.filters.audience.professionals': 'Professionals',
  'bazaar.filters.audience.companies': 'Companies',
  'bazaar.filters.audience.public_administrations': 'PA',
  'bazaar.filters.audience.seniors': 'Seniors',
  'bazaar.filters.audience.immigrants': 'Immigrants',
  'bazaar.filters.audience.unemployed': 'Unemployed',

  'bazaar.filters.level': 'Level',
  'bazaar.filters.level.entry_level': 'Easy',
  'bazaar.filters.level.intermediate_level': 'Intermediate',
  'bazaar.filters.level.advanced_level': 'Advanced',

  'bazaar.filters.funding': 'Funding',
  'bazaar.filters.funding.tuition_fee': 'Tuition fee',
  'bazaar.filters.funding.sponsor': 'Sponsor',
  'bazaar.filters.funding.grant': 'Grant',
  'bazaar.filters.funding.crowdfunding': 'Crowdfunding',
  'bazaar.filters.funding.self_financed': 'Self-financed',

  'bazaar.filters.teachActivity.lecture_performance': 'Lecture performance',
  'bazaar.filters.teachActivity.labs_seminary': 'Laboratory - Seminar',
  'bazaar.filters.teachActivity.xyz_format': 'XYZ Format',
  'bazaar.filters.teachActivity.cultural_event': 'Cultural Events',
  'bazaar.filters.teachActivity.vertical_format': 'Vertical Format',
  'bazaar.filters.teachActivity.machine_usage': 'Machinery Usage',

  'bazaar.filters.eventActivity.talk': 'Talk',
  'bazaar.filters.eventActivity.projection': 'Film/documentary projection',
  'bazaar.filters.eventActivity.exposition': 'Work presentation (books, installations, etc.)',
  'bazaar.filters.eventActivity.workshop': 'Workshop / Seminar',
  'bazaar.filters.eventActivity.performance': 'Performance',

  'bazaar.filters.recurringEntity.weekly': 'Weekly',
  'bazaar.filters.recurringEntity.monthly': 'Monthly',
  'bazaar.filters.recurringEntity.yearly': 'Annual',

  'bazaar.filters.mine.mines': 'mine',
  'bazaar.filters.mine.all': 'all',

  'bazaar.filters.all': 'All',

  'bazaar.proposeBtn': `<i class="sos-icon edit"></i> Submit <i class="sos-icon edit"></i>`,

  'bazaar.propose.modal.title': 'What would you like to do?',
  'bazaar.propose.modal.learn': 'Learn something',
  'bazaar.propose.modal.teach': 'Teach something',
  'bazaar.propose.modal.research': 'A research project',
  'bazaar.propose.modal.event': 'An event',

  'bazaar.framework.teach': 'Teaching',
  'bazaar.framework.learn': 'Teaching',
  'bazaar.framework.event': 'Event',
  'bazaar.framework.research': 'Research',
  'bazaar.framework.teach.short': 'T',
  'bazaar.framework.learn.short': 'T',
  'bazaar.framework.event.short': 'E',
  'bazaar.framework.research.short': 'R',

  'bazaar.sort.score': 'Impact',
  'bazaar.sort.date': 'Latest',
  'bazaar.sort.alpha': 'A-Z',

  'bazaar.comments': 'comment',
  'bazaar.addFavorites': 'add to favorites',
  'bazaar.removeFavorites': 'remove from favorites',
  'bazaar.edit': 'modify',

  'bazaar.details.pageTitle': '{{title}} - Ideas Bazaar - La Scuola Open Source',
  'bazaar.details.level': 'Level:',
  'bazaar.details.topics': 'Tags:',
  'bazaar.details.score': 'Impact:',
  'bazaar.details.hours': 'hours',
  'bazaar.details.hour': 'hour',
  'bazaar.details.recurring.days': 'Recurring meetings of',
  'bazaar.details.recurring.day': 'Recurring meeting of',
  'bazaar.details.recurring.weeks': 'weeks',
  'bazaar.details.recurring.week': 'week',
  'bazaar.details.recurring.months': 'months',
  'bazaar.details.recurring.month': 'month',
  'bazaar.details.recurring.years': 'years',
  'bazaar.details.recurring.year': 'year',
  'bazaar.details.recurring.every': 'every',
  'bazaar.details.fixedDays.meetings': 'meetings of',
  'bazaar.details.fixedDays.meeting': 'meetings of',
  'bazaar.details.what': 'Abstract:',
  'bazaar.details.program': 'Program:',
  'bazaar.details.teach.guests': 'Teacher:',
  'bazaar.details.teach.noGuests': 'no teacher',
  'bazaar.details.learn.guests': 'Teachers:',
  'bazaar.details.learn.noGuests': 'no teacher',
  'bazaar.details.event.guests': 'Guests:',
  'bazaar.details.event.noGuests': 'no guest',
  'bazaar.details.positions': 'Required skills',
  'bazaar.details.positions.peopleKnow': 'people who know',
  'bazaar.details.positions.personKnows': 'person who knows',
  'bazaar.details.deadline': 'Deadline:',
  'bazaar.details.duration': 'will last',
  'bazaar.details.duration.days': 'days',
  'bazaar.details.duration.day': 'day',

  'bazaar.interact.agrees': 'Like',
  'bazaar.interact.wishes': 'Wish',
  'bazaar.interact.favorites': 'Favorite',
  'bazaar.interact.comments': 'Comments',

  'bazaar.propose.learn.title': 'I\'d like to learn - La Scuola Open Source',
  'bazaar.propose.learn.heading': `I want to <strong>learn</strong>`,
  'bazaar.propose.learn.subhead': `Tell us what you'd like to learn!`,

  'bazaar.propose.teach.title': 'I\'d like to teach - La Scuola Open Source',
  'bazaar.propose.teach.heading': `I want to <strong>teach</strong>`,
  'bazaar.propose.teach.subhead': `Tell us what you'd like to teach!`,

  'bazaar.propose.event.title': 'Propose an event - La Scuola Open Source',
  'bazaar.propose.event.heading': `<strong>Entertainment</strong>`,
  'bazaar.propose.event.subhead': `Tell us your idea!`,

  'bazaar.propose.research.title': 'Research Project - La Scuola Open Source',
  'bazaar.propose.research.heading': `<strong>Research</strong>project`,
  'bazaar.propose.research.subhead': `Tell us your idea!`,

  'bazaar.propose.saved.title': `We received <strong>your idea</strong>`,
  'bazaar.propose.saved.subtitle': `You will find it in the Ideas Bazaar`,
  'bazaar.propose.saved.bazaar': `
    <i class="sos-icon comment text-white"></i> Go to the bazaar
  `,
  'bazaar.propose.saved.edit': `
    <i class="sos-icon edit text-white"></i> Modify your idea
  `,

  'bazaar.propose.title': 'Activity Title',
  'bazaar.propose.locationSOS': 'The activity is kept at SOS',
  'bazaar.propose.locationCustom': 'The activity is kept elsewhere',
  'bazaar.propose.activityType': 'What\'s the area of interest?',
  'bazaar.propose.frameworks': 'Type of activity',
  'bazaar.propose.audience': 'What\'s your target?',
  'bazaar.propose.level': 'What\'s the difficulty level of the activity?',
  'bazaar.propose.topics': 'What are the topics of the activity?',
  'bazaar.propose.topics.add': 'Add',
  'bazaar.propose.meetings': 'Describe the typology of meetings',
  'bazaar.propose.fixedDays': 'Finite number of meetings',
  'bazaar.propose.recurring': 'Recurring activity',
  'bazaar.propose.fixedDays.add': 'Add set of meetings',
  'bazaar.propose.fixedDays.remove': 'Remove set of meetings',
  'bazaar.propose.fixedDays.days': 'Number of days',
  'bazaar.propose.fixedDays.hours': 'Number of hours',
  'bazaar.propose.recurring.hours': 'Hours per meeting',
  'bazaar.propose.recurring.days': 'Weekly meetings',
  'bazaar.propose.recurring.every': 'Skip',
  'bazaar.propose.recurring.entity': 'Recurrency type',
  'bazaar.propose.dates': 'Select days and time',
  'bazaar.propose.dates.add': 'Add date',
  'bazaar.propose.dates.remove': 'Remove date',
  'bazaar.propose.dates.date': 'Date',
  'bazaar.propose.dates.startTime': 'Start time',
  'bazaar.propose.dates.endTime': 'End time',
  'bazaar.propose.requiredResources': 'Required resources',
  'bazaar.propose.requiredSpaces': 'What spaces are required?',
  'bazaar.propose.maxParticipants': 'Maximum number of partecipants',
  'bazaar.propose.teachers': 'Define possible teachers for the activity',
  'bazaar.propose.teacher.add': '+ Teacher',
  'bazaar.propose.addedTeachers': 'Teachers',
  'bazaar.propose.tutor.add': '+ Tutor',
  'bazaar.propose.teachers.none': 'No teacher',
  'bazaar.propose.tutors': 'Define possible tutors for the activity',
  'bazaar.propose.addedTutors': 'Tutors',
  'bazaar.propose.tutors.none': 'No tutor',
  'bazaar.propose.guest.firstName': 'Name',
  'bazaar.propose.guest.lastName': 'Last name',
  'bazaar.propose.guest.title': 'Title',
  'bazaar.propose.guest.remove': 'Remove',
  'bazaar.propose.programDetails': 'Describe the meeting schedule as a whole',
  'bazaar.propose.meetingDetails': 'Describe the development of each meeting',
  'bazaar.propose.outputDetails': 'Describe the expected outputs in qualitative and quantitative terms',
  'bazaar.propose.valueDetails': 'Abstract of the activity',
  'bazaar.propose.research.valueDetails': 'Abstract of the research project',
  'bazaar.propose.motivation': 'Why do you propose it?',
  'bazaar.propose.learn.motivation': 'Program of the activity',
  'bazaar.propose.research.motivation': 'Describe the structure of the research project',
  'bazaar.propose.funding': 'How the activity is economically supported?',
  'bazaar.propose.costs': 'What should be the cost, according to you?',
  'bazaar.propose.create': 'Submit your idea',
  'bazaar.propose.update': 'Update your idea',
  'bazaar.propose.guests': 'Expected guests',
  'bazaar.propose.guest.add': '+ Guest',
  'bazaar.propose.addedGuest': 'Added guests',
  'bazaar.propose.guests.none': 'No guest',
  'bazaar.propose.organizerRole': 'Your role',
  'bazaar.propose.isOrganizer': 'Organizator',
  'bazaar.propose.isNotOrganizer': 'Guest',
  'bazaar.propose.bookingRequired': 'Is booking required?',
  'bazaar.propose.bookingIsRequired': 'Yes',
  'bazaar.propose.bookingIsNotRequired': 'No',
  'bazaar.propose.organizationName': 'Organization / Informal Group name',
  'bazaar.propose.positions': 'How many and which skills are required to realize it?',
  'bazaar.propose.positions.add': 'Add skill',
  'bazaar.propose.positions.remove': 'Remove skill',
  'bazaar.propose.positions.people': 'People',
  'bazaar.propose.positions.skills': 'Required skills',
  'bazaar.propose.deadline': 'When does the project start?',
  'bazaar.propose.duration': 'How long the project is?',
  'bazaar.propose.alerts': `
    <strong>Error!</strong> An error occurred while submitting your request. Check those fields and try again.`,

  'bazaar.comments.title': 'Comments',
  'bazaar.comments.agree': 'I like it',
  'bazaar.comments.wish': 'Suggest a variation',
  'bazaar.comments.wishAlert': 'Let us know what you\'d change',
  'bazaar.comments.comment': 'Write a comment:',
  'bazaar.comments.error': 'Comment not saved correctly...',
  'bazaar.comments.send': 'Enter',

  'membership.title': 'Your SOS membership - La Scuola Open Source',
  'membership.heading': 'Membership',
  'membership.type': 'Type',
  'membership.requestNew': 'ACTIVE',
  'membership.cancelRequest': 'DELETE REQUEST',
  'membership.requestRenewal': 'RENEWAL',
  'membership.cancelRenewal': 'DELETE RENEWAL',
  'membership.cancelActive': 'SUSPEND',

  'membership.bottom.text': `
    <strong>The membership is free for all.</strong>
    <p> It's possible to request an "upgrade" (charged) of {{memberships}} different typology, depending on necessities:</p>
  `,
  'membership.priceYear': '/ year',

  'membership.base.title': 'BASE',
  'membership.base.list': `
    <ul>
        <li>propose anything;</li>
        <li>see all ideas;</li>
        <li>discuss and evaluate ideas;</li>
        <li>specify your skills;</li>
        <li>search people and skills;</li>
        <li>search activities and ideas;</li>
        <li>join a project;</li>
    </ul>
  `,

  'activities.type.teach': 'Teaching',
  'activities.type.event': 'Event',
  'activities.type.research': 'Research',

  'activities.activityTypes.teach.lecture_performance': 'Lessons',
  'activities.activityTypes.teach.labs_seminary': 'Workshops / Seminars',
  'activities.activityTypes.teach.xyz_format': 'XYZ Format',
  'activities.activityTypes.teach.cultural_event': 'Cultural Events',
  'activities.activityTypes.teach.vertical_format': 'Vertical Formats',
  'activities.activityTypes.teach.machine_usage': 'Machinery Usage',

  'activities.activityTypes.event.talk': 'Talk',
  'activities.activityTypes.event.projection': 'Film/documentary projection',
  'activities.activityTypes.event.exposition': 'Works Presentations',
  'activities.activityTypes.event.workshop': 'Workshop / Seminar',
  'activities.activityTypes.event.performance': 'Performance',

  'activities.title': 'Activity - La Scuola Open Source',
  'activities.heading': `<strong>Activity</strong> schedule`,
  'activities.none': 'No activity schedule',

  'activities.teach': 'Teaching',
  'activities.teach.date': 'date:',
  'activities.teach.deadline': 'deadline:',
  'activities.teach.deadline.closed': 'expired',
  'activities.teach.topics': 'tags:',
  'activities.teach.teachers': 'teachers:',

  'activities.event': 'Events',
  'activities.event.date': 'date:',
  'activities.event.deadline': 'deadline:',
  'activities.event.deadline.closed': 'expired',
  'activities.event.topics': 'tags:',
  'activities.event.guests': 'guests:',

  'activities.research': 'Projects',
  'activities.research.start': 'start:',
  'activities.research.call': 'call:',
  'activities.research.call.open.s': '1 open position',
  'activities.research.call.open.p': '{{roles}} open positions',
  'activities.research.call.closed': 'no open position',
  'activities.research.topics': 'tags:',
  'activities.research.owner': 'project manager:',

  'activities.teachPage.title': 'Teaching - La Scuola Open Source',
  'activities.teachPage.heading': 'Teaching',
  'activities.teachPage.subhead': `
    <i class="sos-icon right-arrow"></i> All activities <i class="sos-icon left-arrow"></i>
  `,

  'activities.eventPage.title': 'Events - La Scuola Open Source',
  'activities.eventPage.heading': 'Events',
  'activities.eventPage.subhead': `
    <i class="sos-icon right-arrow"></i> All activities <i class="sos-icon left-arrow"></i>
  `,

  'activities.researchPage.title': 'Projects - La Scuola Open Source',
  'activities.researchPage.heading': 'Projects',
  'activities.researchPage.subhead': `
    <i class="sos-icon right-arrow"></i> All activities <i class="sos-icon left-arrow"></i>
  `,

  'activity.favorite.add': 'Save favorite',
  'activity.favorite.remove': 'It\'s on your favorites',

  'activity.teachEvent.title': '{{title}} - La Scuola Open Source',
  'activity.teachEvent.activityType': 'Activity type:',
  'activity.teachEvent.topics': 'tags:',
  'activity.teachEvent.requiredSkills': 'required skills:',
  'activity.teachEvent.acquiredSkills': 'acquired skills:',
  'activity.teachEvent.dates': 'dates:',
  'activity.teachEvent.level': 'Level of difficulty:',
  'activity.teachEvent.costs': 'Activity cost:',
  'activity.teachEvent.costsFree': 'FREE',
  'activity.teachEvent.deadline': 'deadline:',
  'activity.teachEvent.minParticipants': 'min. participants:',
  'activity.teachEvent.maxParticipants': 'max. participants:',
  'activity.teachEvent.subscriptions': 'number of applicants:',
  'activity.teachEvent.teachers': 'Teachers:',
  'activity.teachEvent.guests': 'Guests:',
  'activity.teachEvent.description': 'What is it about?',
  'activity.teachEvent.outputDescription': 'What will we work on?',
  'activity.teachEvent.program': 'How does it work?',

  'activity.teachEvent.subscribe': 'Apply',
  'activity.teachEvent.paypal': 'PayPal',
  'activity.teachEvent.credit': 'Credit card',
  'activity.teachEvent.wire': 'Bank transfer',
  'activity.teachEvent.credit.number': 'Credit card number',
  'activity.teachEvent.credit.cvv': 'CVV',
  'activity.teachEvent.credit.expirationDate': 'Expiring date',
  'activity.teachEvent.credit.submit': 'Send payment',
  'activities.teachEvent.credit.error': 'Unvalid data. Verify and try again',
  'activities.teachEvent.credit.error.number': 'Unvalid card number',
  'activities.teachEvent.credit.error.cvv': 'Unvalid CVV',
  'activities.teachEvent.credit.error.expirationDate': 'Unvalid expiring date.',
  'activity.teachEvent.wire.alert': `
    Once saved, CRO ca't be modifyed. <b>Verify your data before proceeding</b>.`,
  'activity.teachEvent.wire.cro': 'CRO',
  'activity.teachEvent.wire.submit': 'Send payment',

  'activity.teachEvent.subscription.confirmed.payed': `
    <b>Congratulation, your application was successful!</b>
   In case you chose the bank transfer option, wait for our staff to verify the CRO number.
  `,
  'activity.teachEvent.subscription.confirmed': `
    <b>Congratulation, your application was successful!</b>
  `,
  'activity.teachEvent.subscription.title': 'You subscribed to this activity',
  'activity.teachEvent.subscription.date': 'Subscription date:',
  'activity.teachEvent.subscription.paymentMethod': 'Payment method:',
  'activity.teachEvent.subscription.verified': 'Payment verified',
  'activity.teachEvent.subscription.verifiedFalse': 'Unverified payment',
  'activity.teach.contact': 'Request scholarship',
  'activity.teach.contact.subject': 'Request scholarship - {{title}}',
  'activity.event.contact': 'Contact staff',
  'activity.event.contact.subject': 'Contact staff - {{title}}',


  'activity.research.title': '{{title}} - La Scuola Open Source',
  'activity.research.deadline': 'Application Deadline:',
  'activity.research.projectLink': 'Project Repository:',
  'activity.research.projectLink.value': 'Link to project',
  'activity.research.state': 'Project state:',
  'activity.research.state.terminated': 'finished',
  'activity.research.state.ongoing': 'ongoing',
  'activity.research.valueDetails': 'Project Abstract',
  'activity.research.motivation': 'How did you get the idea?',
  'activity.research.roles': 'Open positions',
  'activity.research.role.apply': 'Join the team',
  'activity.research.role.unapply': 'Unapply.',
  'activity.research.team': 'Team',
  'activity.research.apply.motivation': 'State your motivation',
  'activity.research.apply.btn': 'Send application',
  'activity.research.applications.show': 'Show applications',
  'activity.research.applications.hide': 'Hide applications',
  'activity.research.contact': 'Contact team',
  'activity.research.contact.subject': 'Contact team - {{title}}',
  'activity.research.donate': 'Donate',


  'paymentMethods.paypal': 'PayPal',
  'paymentMethods.credit_card': 'Credit card',
  'paymentMethods.wire_transfer': 'Bank transfer',


  'fablab.title': 'FabLab - La Scuola Open Source',
  'fablab.heading': 'Machines',

  'fablab.machine': 'Machine:',
  'fablab.machine.workArea': 'Work area',
  'fablab.machine.maxHeight': 'Maximum hight',
  'fablab.machine.metal': 'Metallic material',
  'fablab.machine.nonMetal': 'Non metallic material',
  'fablab.machine.cuts': 'Cutting material',
  'fablab.machine.engraves': 'Engraving material',
  'fablab.machine.priceHour': 'Price per hour',
  'fablab.machine.operator': 'Operator',
  'fablab.machine.operator.yes': 'YES',
  'fablab.machine.operator.no': 'NO',
  'fablab.machine.book': 'BOOK',

  'fablab.calendar.select.day': 'Choose the date',
  'fablab.calendar.select.hour': 'Choose the hour',
  'fablab.calendar.selected': 'Your selection',
  'fablab.calendar.notAvailable': 'Unavailable or already booked',

  'fablab.reservation.operator': 'With operator',
  'fablab.reservation.totalPrice': 'Total <b>estimated</b> price:',
  'fablab.reservation.send': 'Send reservation',
  'fablab.reservation.confirmation': 'Reservation successfully sent!',
  'fablab.reservation.failure': 'An error occurred and your reservation wasn\'t saved ' +
    'try again or contact us if the problem persists.',

  'fablab.quotation.heading': `Request a <strong>budget</strong>`,
  'fablab.quotation.machines': 'What machine do you want to use?',
  'fablab.quotation.realizationOf': 'What do you want to realize?',
  'fablab.quotation.send': 'SEND REQUEST',
  'fablab.quotation.alert.success': 'Request successfully sent',
  'fablab.quotation.alert.failed': 'An error occurred and your request wasn\'t saved, ' +
    'try again or contact us if the problem persists',


  'calendar.weekday.mon': 'mon',
  'calendar.weekday.tue': 'tue',
  'calendar.weekday.wed': 'wed',
  'calendar.weekday.thu': 'thu',
  'calendar.weekday.fri': 'fri',
  'calendar.weekday.sat': 'sat',
  'calendar.weekday.sun': 'sun',
  'calendar.month.0': 'January',
  'calendar.month.1': 'February',
  'calendar.month.2': 'March',
  'calendar.month.3': 'April',
  'calendar.month.4': 'May',
  'calendar.month.5': 'June',
  'calendar.month.6': 'July',
  'calendar.month.7': 'August',
  'calendar.month.8': 'September',
  'calendar.month.9': 'October',
  'calendar.month.10': 'November',
  'calendar.month.11': 'December',


  'util.schedule.day': 'day',
  'util.schedule.days': 'days',
  'util.schedule.for': 'per',
  'util.schedule.forTotal': 'for an amount of',
  'util.schedule.hour': 'hour',
  'util.schedule.hours': 'hours',
  'util.schedule.recurring.weeks': 'weeks',
  'util.schedule.recurring.week': 'week',
  'util.schedule.recurring.months': 'months',
  'util.schedule.recurring.month': 'month',
  'util.schedule.recurring.years': 'years',
  'util.schedule.recurring.year': 'year',
  'util.schedule.recurring.every': 'every',

  'true': 'Yes',
  'false': 'No'

};
