export const LANG_IT_VALUES = {
  'nav.home': 'Home',
  'nav.profile': 'Il mio profilo',
  'nav.favorites': 'I miei preferiti',
  'nav.bazaar': '',
  'nav.activities': 'Attività (corsi, eventi, progetti in corso)',
  'nav.membership': 'Membership',
  'nav.propose': 'Proponi un\'idea',
  'nav.fablab': 'Laboratorio',
  'nav.it': 'Italiano',
  'nav.en': 'English',
  'nav.rules': 'Regolamento',
  'nav.logout': 'Logout',
  'nav.login': 'Join',

  'loading.load': 'Caricamento...',
  'loading.login': 'Accedi',

  'errorPage.title': 'Errore - Open Design School',
  'errorPage.text': 'ERROR {{code}}',

  'favorites.title': 'I tuoi preferiti - Open Design School',
  'favorites.heading': `I tuoi <strong>preferiti</strong>`,
  'favorites.users': 'Persone',
  'favorites.ideas': 'Idee e progetti',
  'favorites.activities': 'Attività',

  'home.title': 'Open Design School',

  'home.welcome.title': 'Benvenuto a bordo!',
  'home.welcome.body': `
    Il <b>Gestionale per Nuove Istituzioni</b><br />
    Connette <b>persone, idee, progetti e competenze</b><br />
    per generare <b>nuove possibilità</b>.
  `,

  'home.complete.profile.txt': 'Completa la tua registrazione:',
  'home.complete.profile.btn.profile': `<i class="sos-icon edit"></i> Completa il tuo profilo`,
  'home.complete.profile.btn.member': `<i class="sos-icon edit"></i> Scopri i piani di membership`,

  'home.search.value': `<b>Persone</b> / <b>Idee</b> / <b>Attività</b>`,
  'home.search.skills': `<b>Competenze</b>`,
  'home.search.btn': 'Cerca',
  'home.search.skills.show': 'Mostra ricerca per competenze',
  'home.search.skills.hide': 'Nascondi ricerca per competenze',
  'home.search.skills.matchAll': 'Ricerca chi ha tutte le competenze selezionate',
  'home.search.noResult': 'La ricerca non ha restituito alcun risultato.',
  'home.search.users': 'Persone',
  'home.search.ideas': 'Idee',
  'home.search.activities': 'Attività',

  'card.user.skills': 'Competenze',
  'card.user.email': 'E-mail',
  'card.user.tel': 'Telefono',

  'card.idea.topics': 'Tematiche',
  'card.idea.type': 'Tipologia',
  'card.idea.creator': 'Responsabile',

  'card.activity.topics': 'Tematiche',
  'card.activity.startDate': 'Data',
  'card.activity.skills': 'Competenze',
  'card.activity.type': 'Tipologia',

  'profile.title': '{{user}} - Open Design School',
  'profile.title.me': 'Il mio profilo - Open Design School',
  'profile.edit.firstName': 'Nome',
  'profile.edit.lastName': 'Cognome',
  'profile.edit.title': 'La tua qualifica',
  'profile.edit.bio': 'La tua bio',
  'profile.edit.skills': 'making, coding, design...',
  'profile.edit.telephone': '+39 123456789',
  'profile.edit.email': 'user@email.com',
  'profile.edit.city': 'Città',
  'profile.edit.city.search': 'Cerca città',
  'profile.edit.city.empty': 'Lascia vuoto',
  'profile.edit.city.other': 'Fuori dall\'Italia',
  'profile.edit.city.noneFound': 'Nessuna città trovata',
  'profile.alert.changedEmail': `Segui il link all'indirizzo <b>{{email}}</b> per confermare la nuova email`,
  'profile.skills': 'Competenze:',
  'profile.telephone': 'Telefono:',
  'profile.email': 'Email:',
  'profile.city': 'Città:',
  'profile.favorites.remove': 'Rimuovi dai preferiti',
  'profile.favorites.add': 'Aggiungi ai preferiti',
  'profile.favorites': 'Vedi i preferiti',

  'profile.skill.add': 'Aggiungi',

  'profile.reservations': 'Prenotazioni Laboratorio',
  'profile.reservations.title': 'Prenotazioni macchine',
  'profile.reservations.machine': 'Macchina',
  'profile.reservations.operator': 'Operatore',
  'profile.reservations.dates': 'Date',
  'profile.reservations.totalPrice': 'Costo totale',


  'bazaar.title': 'Bazaar delle Idee - Open Design School',
  'bazaar.heading': `<strong>Bazaar</strong> delle <strong>idee</strong>`,
  'bazaar.subhead': 'Proponi, cerca, discuti un\'idea o un progetto.',

  'bazaar.filters.framework.teaching_framework': 'Didattica',
  'bazaar.filters.framework.research_framework': 'Ricerca',
  'bazaar.filters.framework.entertainment_framework': 'Evento',
  'bazaar.filters.framework.all': 'Tutti',

  'bazaar.filters.audience': 'Pubblico',
  'bazaar.filters.audience.kids': 'Bambini',
  'bazaar.filters.audience.teenagers': 'Ragazzi',
  'bazaar.filters.audience.students': 'Studenti',
  'bazaar.filters.audience.researchers': 'Ricercatori',
  'bazaar.filters.audience.professionals': 'Professionisti',
  'bazaar.filters.audience.companies': 'Imprese',
  'bazaar.filters.audience.public_administrations': 'PA',
  'bazaar.filters.audience.seniors': 'Pensionati',
  'bazaar.filters.audience.immigrants': 'Immigrati',
  'bazaar.filters.audience.unemployed': 'Disoccupati',

  'bazaar.filters.level': 'Livello',
  'bazaar.filters.level.entry_level': 'Facile',
  'bazaar.filters.level.intermediate_level': 'Medio',
  'bazaar.filters.level.advanced_level': 'Difficile',

  'bazaar.filters.funding': 'Funding',
  'bazaar.filters.funding.tuition_fee': 'Quota di partecipazione',
  'bazaar.filters.funding.sponsor': 'Sponsor',
  'bazaar.filters.funding.grant': 'Bando',
  'bazaar.filters.funding.crowdfunding': 'Crowdfunding',
  'bazaar.filters.funding.self_financed': 'Autofinanziato',

  'bazaar.filters.teachActivity.lecture_performance': 'Lezioni performance',
  'bazaar.filters.teachActivity.labs_seminary': 'Laboratori - Seminari',
  'bazaar.filters.teachActivity.xyz_format': 'Format orizzontali',
  'bazaar.filters.teachActivity.cultural_event': 'Eventi culturali',
  'bazaar.filters.teachActivity.vertical_format': 'Format verticali',
  'bazaar.filters.teachActivity.machine_usage': 'Utilizzo macchine',

  'bazaar.filters.eventActivity.talk': 'Talk',
  'bazaar.filters.eventActivity.projection': 'Proiezione di film/documentario non protetto da copyright',
  'bazaar.filters.eventActivity.exposition': 'Presentazione di opere (libri, installazioni, etc.)',
  'bazaar.filters.eventActivity.workshop': 'Workshop / Seminario',
  'bazaar.filters.eventActivity.performance': 'Performance',

  'bazaar.filters.recurringEntity.weekly': 'Settimanale',
  'bazaar.filters.recurringEntity.monthly': 'Mensile',
  'bazaar.filters.recurringEntity.yearly': 'Annuale',

  'bazaar.filters.mine.mines': 'le mie',
  'bazaar.filters.mine.all': 'tutte',

  'bazaar.filters.all': 'Tutti',

  'bazaar.proposeBtn': `<i class="sos-icon edit"></i> proponi <i class="sos-icon edit"></i>`,

  'bazaar.propose.modal.title': 'Cosa vuoi fare?',
  'bazaar.propose.modal.learn': 'Imparare qualcosa',
  'bazaar.propose.modal.teach': 'Insegnare qualcosa',
  'bazaar.propose.modal.research': 'Un progetto di ricerca',
  'bazaar.propose.modal.event': 'Un evento',

  'bazaar.framework.teach': 'Didattica',
  'bazaar.framework.learn': 'Didattica',
  'bazaar.framework.event': 'Evento',
  'bazaar.framework.research': 'Ricerca',
  'bazaar.framework.teach.short': 'D',
  'bazaar.framework.learn.short': 'D',
  'bazaar.framework.event.short': 'E',
  'bazaar.framework.research.short': 'R',

  'bazaar.sort.score': 'Impatto',
  'bazaar.sort.date': 'Recenti',
  'bazaar.sort.alpha': 'A-Z',

  'bazaar.comments': 'commenta',
  'bazaar.addFavorites': 'aggiungi ai preferiti',
  'bazaar.removeFavorites': 'rimuovi dai preferiti',
  'bazaar.edit': 'modifica',

  'bazaar.details.pageTitle': '{{title}} - Bazaar delle Idee - Open Design School',
  'bazaar.details.level': 'Livello:',
  'bazaar.details.topics': 'Tags:',
  'bazaar.details.score': 'Impatto:',
  'bazaar.details.hours': 'ore',
  'bazaar.details.hour': 'ora',
  'bazaar.details.recurring.days': 'appuntamenti periodici da',
  'bazaar.details.recurring.day': 'appuntamento periodico da',
  'bazaar.details.recurring.weeks': 'settimane',
  'bazaar.details.recurring.week': 'settimana',
  'bazaar.details.recurring.months': 'mesi',
  'bazaar.details.recurring.month': 'mese',
  'bazaar.details.recurring.years': 'anni',
  'bazaar.details.recurring.year': 'anno',
  'bazaar.details.recurring.every': 'ogni',
  'bazaar.details.fixedDays.meetings': 'appuntamenti da',
  'bazaar.details.fixedDays.meeting': 'appuntamento da',
  'bazaar.details.what': 'Abstract:',
  'bazaar.details.program': 'Programma:',
  'bazaar.details.teach.guests': 'Docenti:',
  'bazaar.details.teach.noGuests': 'nessun docente',
  'bazaar.details.learn.guests': 'Docenti:',
  'bazaar.details.learn.noGuests': 'nessun docente',
  'bazaar.details.event.guests': 'Ospiti:',
  'bazaar.details.event.noGuests': 'nessun ospite',
  'bazaar.details.positions': 'Competenze richieste',
  'bazaar.details.positions.peopleKnow': 'persone che conoscano',
  'bazaar.details.positions.personKnows': 'persona che conosca',
  'bazaar.details.deadline': 'Deadline:',
  'bazaar.details.duration': 'durerà',
  'bazaar.details.duration.days': 'giorni',
  'bazaar.details.duration.day': 'giorno',

  'bazaar.interact.agrees': 'Mi piace',
  'bazaar.interact.wishes': 'Proposta',
  'bazaar.interact.favorites': 'Preferito',
  'bazaar.interact.comments': 'Commenti',

  'bazaar.propose.learn.title': 'Voglio imparare - Open Design School',
  'bazaar.propose.learn.heading': `Voglio <strong>imparare</strong>`,
  'bazaar.propose.learn.subhead': `Raccontaci cosa desideri imparare!`,

  'bazaar.propose.teach.title': 'Voglio insegnare - Open Design School',
  'bazaar.propose.teach.heading': `Voglio <strong>insegnare</strong>`,
  'bazaar.propose.teach.subhead': `Raccontaci la tua idea!`,

  'bazaar.propose.event.title': 'Proponi un evento - Open Design School',
  'bazaar.propose.event.heading': `<strong>Intrattenimento</strong>`,
  'bazaar.propose.event.subhead': `Raccontaci cosa hai in mente!`,

  'bazaar.propose.research.title': 'Progetto di ricerca - Open Design School',
  'bazaar.propose.research.heading': `Progetto di <strong>ricerca</strong>`,
  'bazaar.propose.research.subhead': `Raccontaci la tua idea!`,

  'bazaar.propose.saved.title': `Abbiamo ricevuto <strong>la tua proposta</strong>`,
  'bazaar.propose.saved.subtitle': `Puoi trovarla nel Bazaar delle idee`,
  'bazaar.propose.saved.bazaar': `
    <i class="sos-icon comment text-white"></i> Vai al bazaar
  `,
  'bazaar.propose.saved.edit': `
    <i class="sos-icon edit text-white"></i> Modifica la tua idea
  `,

  'bazaar.propose.title': 'Titolo dell\'attività',
  'bazaar.propose.locationSOS': 'L\'attività si svolge alla ODS',
  'bazaar.propose.locationCustom': 'L\'attività si svolge altrove',
  'bazaar.propose.activityType': 'In quali ambiti rientra l\'attività proposta?',
  'bazaar.propose.frameworks': 'Tipologia di attività',
  'bazaar.propose.audience': 'Qual è il pubblico della tua idea?',
  'bazaar.propose.level': 'Qual è il livello di difficoltà dell\'attività?',
  'bazaar.propose.topics': 'Quali argomenti saranno trattati durante l\'attività?',
  'bazaar.propose.topics.add': 'Aggiungi',
  'bazaar.propose.meetings': 'Descrivi il tipo di incontri',
  'bazaar.propose.fixedDays': 'Numero finito di incontri',
  'bazaar.propose.recurring': 'Attività periodica',
  'bazaar.propose.fixedDays.add': 'Aggiungi set di incontri',
  'bazaar.propose.fixedDays.remove': 'Rimuovi set di incontri',
  'bazaar.propose.fixedDays.days': 'Numero di giorni',
  'bazaar.propose.fixedDays.hours': 'Numero di ore',
  'bazaar.propose.recurring.hours': 'Ore per incontro',
  'bazaar.propose.recurring.days': 'Incontri settimanali',
  'bazaar.propose.recurring.every': 'Salta',
  'bazaar.propose.recurring.entity': 'Tipo di ricorrenza',
  'bazaar.propose.dates': 'Indica le date di svolgimento e gli orari',
  'bazaar.propose.dates.add': 'Aggiungi data',
  'bazaar.propose.dates.remove': 'Rimuovi data',
  'bazaar.propose.dates.date': 'Data',
  'bazaar.propose.dates.startTime': 'Orario d\'inizio',
  'bazaar.propose.dates.endTime': 'Orario di fine',
  'bazaar.propose.requiredResources': 'Risorse necessarie',
  'bazaar.propose.requiredSpaces': 'Di quali spazi hai bisogno?',
  'bazaar.propose.maxParticipants': 'Numero massimo di partecipanti',
  'bazaar.propose.teachers': 'Definisci eventuali docenti per l\'attività',
  'bazaar.propose.teacher.add': '+ Docente',
  'bazaar.propose.addedTeachers': 'Docenti',
  'bazaar.propose.tutor.add': '+ Tutor',
  'bazaar.propose.teachers.none': 'Nessun docente',
  'bazaar.propose.tutors': 'Definisci eventuali tutor per l\'attività',
  'bazaar.propose.addedTutors': 'Tutors',
  'bazaar.propose.tutors.none': 'Nessun tutor',
  'bazaar.propose.guest.firstName': 'Nome',
  'bazaar.propose.guest.lastName': 'Cognome',
  'bazaar.propose.guest.title': 'Titolo',
  'bazaar.propose.guest.remove': 'Rimuovi',
  'bazaar.propose.programDetails': 'Descrivi il programma di incontri nel suo complesso',
  'bazaar.propose.meetingDetails': 'Descrivi lo svolgimento di ciascun incontro',
  'bazaar.propose.outputDetails': 'Descrivi gli output attesi in termini qualitativi e quantitativi',
  'bazaar.propose.valueDetails': 'Abstract dell\'attività',
  'bazaar.propose.research.valueDetails': 'Abstract del progetto di ricerca',
  'bazaar.propose.motivation': 'Perché lo proponi?',
  'bazaar.propose.learn.motivation': 'Immagina il programma dell\'attività',
  'bazaar.propose.research.motivation': 'Descrivi la struttura del progetto di ricerca',
  'bazaar.propose.funding': 'Come si sostiene economicamente l\'attività?',
  'bazaar.propose.costs': 'Secondo te quale sarebbe il giusto costo per questa attività?',
  'bazaar.propose.create': 'Proponi la tua idea',
  'bazaar.propose.update': 'Aggiorna la tua idea',
  'bazaar.propose.guests': 'Ospite/i previsti',
  'bazaar.propose.guest.add': '+ Ospite',
  'bazaar.propose.addedGuest': 'Ospiti aggiunti',
  'bazaar.propose.guests.none': 'Nessun ospite',
  'bazaar.propose.organizerRole': 'Il tuo ruolo',
  'bazaar.propose.isOrganizer': 'Organizzatore',
  'bazaar.propose.isNotOrganizer': 'Ospite',
  'bazaar.propose.bookingRequired': 'È necessaria la prenotazione?',
  'bazaar.propose.bookingIsRequired': 'Sì',
  'bazaar.propose.bookingIsNotRequired': 'No',
  'bazaar.propose.organizationName': 'Nome Organizzazione / Gruppo informale',
  'bazaar.propose.positions': 'Quante e quali competenze sono necessarie per realizzarla?',
  'bazaar.propose.positions.add': 'Aggiungi competenza',
  'bazaar.propose.positions.remove': 'Rimuovi competenza',
  'bazaar.propose.positions.people': 'Persone',
  'bazaar.propose.positions.skills': 'Competenze richieste',
  'bazaar.propose.deadline': 'Quando inizia il progetto?',
  'bazaar.propose.duration': 'Quanto durerà il progetto?',
  'bazaar.propose.alerts': `
    <strong>Errore!</strong> Si è verificato un errore nell\'inviare la richiesta. Rivedi i seguenti campi e riprova.`,

  'bazaar.comments.title': 'Commenti',
  'bazaar.comments.agree': 'Mi piace',
  'bazaar.comments.wish': 'Suggerisci una modifica',
  'bazaar.comments.wishAlert': 'Facci sapere cosa cambieresti',
  'bazaar.comments.comment': 'Scrivi un commento:',
  'bazaar.comments.error': 'Commento non salvato correttamente...',
  'bazaar.comments.send': 'Invia',

  'membership.title': 'La tua membership ODS - Open Design School',
  'membership.heading': 'Membership',
  'membership.type': 'Tipologia',
  'membership.requestNew': 'ATTIVA',
  'membership.cancelRequest': 'CANCELLA RICHIESTA',
  'membership.requestRenewal': 'RINNOVA',
  'membership.cancelRenewal': 'CANCELLA RINNOVO',
  'membership.cancelActive': 'SOSPENDI',

  'membership.bottom.text': `
    <strong>La membership è gratuita per tutti.</strong>
    <p>È possibile richiedere un "upgrade" (a pagamento) di {{memberships}}
      tipologie differenti, a seconda delle proprie necessità:</p>
  `,
  'membership.priceYear': '/ anno',

  'membership.base.title': 'BASE',
  'membership.base.list': `
    <ul>
      <li>proponi qualsiasi cosa;</li>
      <li>consulta tutte le proposte;</li>
      <li>discuti e valutare le proposte;</li>
      <li>indica le tue competenze;</li>
      <li>cerca persone e competenze;</li>
      <li>cerca attività o idee;</li>
      <li>partecipa a un progetto;</li>
    </ul>
  `,

  'activities.type.teach': 'Didattica',
  'activities.type.event': 'Evento',
  'activities.type.research': 'Ricerca',

  'activities.activityTypes.teach.lecture_performance': 'Lezioni',
  'activities.activityTypes.teach.labs_seminary': 'Laboratori',
  'activities.activityTypes.teach.xyz_format': 'Format orizzontali',
  'activities.activityTypes.teach.cultural_event': 'Eventi culturali',
  'activities.activityTypes.teach.vertical_format': 'Format verticali',
  'activities.activityTypes.teach.machine_usage': 'Utilizzo macchine',

  'activities.activityTypes.event.talk': 'Talk',
  'activities.activityTypes.event.projection': 'Proiezione di film/documentario',
  'activities.activityTypes.event.exposition': 'Presentazione di opere',
  'activities.activityTypes.event.workshop': 'Workshop / Seminario',
  'activities.activityTypes.event.performance': 'Performance',

  'activities.title': 'Attività - Open Design School',
  'activities.heading': `<strong>Attività</strong> in programma`,
  'activities.none': 'Nessun attività in programma',

  'activities.teach': 'Didattica',
  'activities.teach.date': 'data:',
  'activities.teach.deadline': 'deadline:',
  'activities.teach.deadline.closed': 'scaduta',
  'activities.teach.topics': 'tags:',
  'activities.teach.teachers': 'docenti:',

  'activities.event': 'Eventi',
  'activities.event.date': 'data:',
  'activities.event.deadline': 'deadline:',
  'activities.event.deadline.closed': 'scaduta',
  'activities.event.topics': 'tags:',
  'activities.event.guests': 'ospiti:',

  'activities.research': 'Progetti',
  'activities.research.start': 'inizio:',
  'activities.research.call': 'call:',
  'activities.research.call.open.s': '1 posizione aperta',
  'activities.research.call.open.p': '{{roles}} posizioni aperte',
  'activities.research.call.closed': 'nessuna posizione aperta',
  'activities.research.topics': 'tags:',
  'activities.research.owner': 'resp.:',

  'activities.teachPage.title': 'Didattica - Open Design School',
  'activities.teachPage.heading': 'Didattica',
  'activities.teachPage.subhead': `
    <i class="sos-icon right-arrow"></i> Tutte le attività <i class="sos-icon left-arrow"></i>
  `,

  'activities.eventPage.title': 'Eventi - Open Design School',
  'activities.eventPage.heading': 'Eventi',
  'activities.eventPage.subhead': `
    <i class="sos-icon right-arrow"></i> Tutte le attività <i class="sos-icon left-arrow"></i>
  `,

  'activities.researchPage.title': 'Progetti - Open Design School',
  'activities.researchPage.heading': 'Progetti',
  'activities.researchPage.subhead': `
    <i class="sos-icon right-arrow"></i> Tutte le attività <i class="sos-icon left-arrow"></i>
  `,

  'activity.favorite.add': 'Salva preferito',
  'activity.favorite.remove': 'È tra i preferiti',

  'activity.teachEvent.title': '{{title}} - Open Design School',
  'activity.teachEvent.activityType': 'Tipologia di attività:',
  'activity.teachEvent.topics': 'tags:',
  'activity.teachEvent.requiredSkills': 'competenze richieste:',
  'activity.teachEvent.acquiredSkills': 'competenze acquisite:',
  'activity.teachEvent.dates': 'date:',
  'activity.teachEvent.level': 'Livello di difficoltà:',
  'activity.teachEvent.costs': 'Costo dell\'attività:',
  'activity.teachEvent.costsFree': 'GRATUITA',
  'activity.teachEvent.deadline': 'deadline:',
  'activity.teachEvent.minParticipants': 'min. partecipanti:',
  'activity.teachEvent.maxParticipants': 'max. partecipanti:',
  'activity.teachEvent.subscriptions': 'numero di iscritti:',
  'activity.teachEvent.teachers': 'Docenti:',
  'activity.teachEvent.guests': 'Ospiti:',
  'activity.teachEvent.description': 'Di cosa si tratta?',
  'activity.teachEvent.outputDescription': 'A cosa si lavora?',
  'activity.teachEvent.program': 'Come si svolge?',

  'activity.teachEvent.subscribe': 'Iscriviti',
  'activity.teachEvent.paypal': 'PayPal',
  'activity.teachEvent.credit': 'Carte',
  'activity.teachEvent.wire': 'Bonifico',
  'activity.teachEvent.credit.number': 'Numero di carta',
  'activity.teachEvent.credit.cvv': 'CVV',
  'activity.teachEvent.credit.expirationDate': 'Data scadenza',
  'activity.teachEvent.credit.submit': 'Invia pagamento',
  'activities.teachEvent.credit.error': 'Dati non validi. Verifica e riprova',
  'activities.teachEvent.credit.error.number': 'Numero di carta non valido',
  'activities.teachEvent.credit.error.cvv': 'CVV non valido',
  'activities.teachEvent.credit.error.expirationDate': 'Data di scadenza non valida',
  'activity.teachEvent.wire.alert': `
    Una volta salvato, il CRO non può essere modificato. <b>Verifica i dati prima di proseguire</b>.`,
  'activity.teachEvent.wire.cro': 'CRO',
  'activity.teachEvent.wire.submit': 'Invia pagamento',

  'activity.teachEvent.subscription.confirmed.payed': `
    <b>Congratulazioni, iscrizione effettuata con successo!</b>
    Nel caso in cui tu abbia scelto l'opzione bonifico, attendi che il nostro staff verifichi il numero di CRO.
  `,
  'activity.teachEvent.subscription.confirmed': `
    <b>Congratulazioni, iscrizione effettuata con successo!</b>
  `,
  'activity.teachEvent.subscription.title': 'Sei iscritto a quest\'attività',
  'activity.teachEvent.subscription.date': 'Data iscrizione:',
  'activity.teachEvent.subscription.paymentMethod': 'Metodo di pagamento:',
  'activity.teachEvent.subscription.verified': 'Pagamento verificato',
  'activity.teachEvent.subscription.verifiedFalse': 'Pagamento non verificato',
  'activity.teach.contact': 'Richiedi borsa',
  'activity.teach.contact.subject': 'Richiedi borsa - {{title}}',
  'activity.event.contact': 'Contatta staff',
  'activity.event.contact.subject': 'Contatta staff - {{title}}',


  'activity.research.title': '{{title}} - Open Design School',
  'activity.research.deadline': 'Deadline candidature:',
  'activity.research.projectLink': 'Repository del progetto:',
  'activity.research.projectLink.value': 'Link al progetto',
  'activity.research.state': 'Stato del progetto:',
  'activity.research.state.terminated': 'terminato',
  'activity.research.state.ongoing': 'in corso',
  'activity.research.valueDetails': 'Abstract del progetto',
  'activity.research.motivation': 'Come nasce l\'idea?',
  'activity.research.roles': 'Posizioni aperte',
  'activity.research.role.apply': 'Unisciti al team',
  'activity.research.role.unapply': 'Elimina candid.',
  'activity.research.team': 'Team',
  'activity.research.apply.motivation': 'Indica la tua motivazione',
  'activity.research.apply.btn': 'Invia candidatura',
  'activity.research.applications.show': 'Mostra candidature',
  'activity.research.applications.hide': 'Nascondi candidature',
  'activity.research.contact': 'Contatta team',
  'activity.research.contact.subject': 'Contatta team - {{title}}',
  'activity.research.donate': 'Dona',


  'paymentMethods.paypal': 'PayPal',
  'paymentMethods.credit_card': 'Carte',
  'paymentMethods.wire_transfer': 'Bonifico',


  'fablab.title': 'Laboratorio - Open Design School',
  'fablab.heading': 'Macchinari',

  'fablab.machine': 'Macchinario:',
  'fablab.machine.workArea': 'Area di lavoro',
  'fablab.machine.maxHeight': 'Altezza massima',
  'fablab.machine.metal': 'Materiali metallici',
  'fablab.machine.nonMetal': 'Materiali non metallici',
  'fablab.machine.cuts': 'Materiali da taglio',
  'fablab.machine.engraves': 'Materiali da incisione',
  'fablab.machine.priceHour': 'Prezzo orario',
  'fablab.machine.operator': 'Operatore',
  'fablab.machine.operator.yes': 'SÌ',
  'fablab.machine.operator.no': 'NO',
  'fablab.machine.book': 'PRENOTA',

  'fablab.calendar.select.day': 'Scegli il giorno',
  'fablab.calendar.select.hour': 'Scegli l\'orario',
  'fablab.calendar.selected': 'La tua selezione',
  'fablab.calendar.notAvailable': 'Non disponibile o già prenotato',

  'fablab.reservation.operator': 'Con operatore',
  'fablab.reservation.totalPrice': 'Costo lavorazione <b>stimato</b>:',
  'fablab.reservation.send': 'Invia prenotazione',
  'fablab.reservation.confirmation': 'Prenotazione inviata con successo',
  'fablab.reservation.failure': 'La prenotazione non è stata salvata a causa di un errore, ' +
    'riprova in seguito o contattaci se il problema persiste.',

  'fablab.quotation.heading': `Richiedi un <strong>preventivo</strong>`,
  'fablab.quotation.machines': 'Quale macchina vuoi utilizzare?',
  'fablab.quotation.realizationOf': 'Cosa vuoi realizzare?',
  'fablab.quotation.send': 'INVIA LA RICHIESTA',
  'fablab.quotation.alert.success': 'Richiesta inviata con successo',
  'fablab.quotation.alert.failed': 'La richiesta non è stata salvata a causa di un errore, ' +
    'riprova in seguito o contattaci se il problema persiste.',


  'calendar.weekday.mon': 'lun',
  'calendar.weekday.tue': 'mar',
  'calendar.weekday.wed': 'mer',
  'calendar.weekday.thu': 'gio',
  'calendar.weekday.fri': 'ven',
  'calendar.weekday.sat': 'sab',
  'calendar.weekday.sun': 'dom',
  'calendar.month.0': 'Gennaio',
  'calendar.month.1': 'Febbraio',
  'calendar.month.2': 'Marzo',
  'calendar.month.3': 'Aprile',
  'calendar.month.4': 'Maggio',
  'calendar.month.5': 'Giugno',
  'calendar.month.6': 'Luglio',
  'calendar.month.7': 'Agosto',
  'calendar.month.8': 'Settembre',
  'calendar.month.9': 'Ottobre',
  'calendar.month.10': 'Novembre',
  'calendar.month.11': 'Dicembre',


  'util.schedule.day': 'giorno',
  'util.schedule.days': 'giorni',
  'util.schedule.for': 'per',
  'util.schedule.forTotal': 'per un totale di',
  'util.schedule.hour': 'ora',
  'util.schedule.hours': 'ore',
  'util.schedule.recurring.weeks': 'settimane',
  'util.schedule.recurring.week': 'settimana',
  'util.schedule.recurring.months': 'mesi',
  'util.schedule.recurring.month': 'mese',
  'util.schedule.recurring.years': 'anni',
  'util.schedule.recurring.year': 'anno',
  'util.schedule.recurring.every': 'ogni',

  'true': 'Si',
  'false': 'No'
};
